version: "3.8"

services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpw

  mongo-backup:
    image: bo-i-t/docker-mongodump:v1.0.0
    build: https://github.com/bo-i-t/docker-mongodump.git#v1.0.0
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USERNAME=rootuser
      - MONGO_PASSWORD=rootpw
      - MONGO_AUTHENTICATION_DATABASE=admin
      - MONGO_DB=admin
    volumes:
      - /tmp/example-mongodump/:/backup/
      - ./example-cronfile:/etc/cron.d/crontab
